"""Investment idea model for the Overture system."""

import enum
from datetime import datetime
from typing import Any, Optional

from sqlalchemy import Enum, Float, String, Text, func
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base


class IdeaSource(str, enum.Enum):
    """Origin source of an investment idea."""

    NEWS = "news"
    SCREEN = "screen"
    AGENT = "agent"
    USER = "user"
    AGGREGATED = "aggregated"


class IdeaStatus(str, enum.Enum):
    """Lifecycle status of an investment idea."""

    GENERATED = "generated"
    VALIDATING = "validating"
    VALIDATED = "validated"
    REJECTED = "rejected"
    EXECUTING = "executing"
    MONITORING = "monitoring"
    CLOSED = "closed"


class RiskLevel(str, enum.Enum):
    """Risk classification for an investment idea."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    EXTREME = "extreme"


class Timeframe(str, enum.Enum):
    """Expected holding period for an investment idea."""

    INTRADAY = "intraday"
    SHORT_TERM = "short_term"
    MEDIUM_TERM = "medium_term"
    LONG_TERM = "long_term"


class Idea(Base):
    """Represents an investment idea generated by agents or users.

    An idea captures a thesis about an asset or market, including
    its source, risk profile, expected return, and validation status.
    Ideas progress through a lifecycle from generation to closure.
    """

    __tablename__ = "ideas"

    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    source: Mapped[IdeaSource] = mapped_column(
        Enum(IdeaSource, name="idea_source", native_enum=False),
        nullable=False,
    )
    source_url: Mapped[Optional[str]] = mapped_column(String(2048), nullable=True)
    asset_class: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    tickers: Mapped[Optional[list[str]]] = mapped_column(JSON, nullable=True, default=list)
    thesis: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    status: Mapped[IdeaStatus] = mapped_column(
        Enum(IdeaStatus, name="idea_status", native_enum=False),
        nullable=False,
        default=IdeaStatus.GENERATED,
    )
    confidence_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    expected_return: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    risk_level: Mapped[Optional[RiskLevel]] = mapped_column(
        Enum(RiskLevel, name="risk_level", native_enum=False),
        nullable=True,
    )
    timeframe: Mapped[Optional[Timeframe]] = mapped_column(
        Enum(Timeframe, name="timeframe", native_enum=False),
        nullable=True,
    )
    validation_results: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSON, nullable=True, default=dict
    )
    metadata_: Mapped[Optional[dict[str, Any]]] = mapped_column(
        "metadata", JSON, nullable=True, default=dict
    )

    # Relationships
    trades: Mapped[list["Trade"]] = relationship(  # noqa: F821
        "Trade", back_populates="idea", lazy="selectin"
    )

    def __repr__(self) -> str:
        return f"<Idea(id={self.id!r}, title={self.title!r}, status={self.status!r})>"
